-- Conversion table. All the formulas below are based FROM the inch TO [unit here]. Credits to google and its unit converter
GRule.UnitConversion = {
	["unit"] = {
		idx = 1,
		name = "#tool.gruletool.unit.unit",
		sname = "#tool.gruletool.unit.sunit",
		lname = "#tool.gruletool.unit.lunit",
		noscale = true,
		convformula = function(value) return value end,
	},
	["block"] = {
		idx = 2,
		name = "#tool.gruletool.unit.block",
		sname = "#tool.gruletool.unit.sblock",
		lname = "#tool.gruletool.unit.lblock",
		noscale = true,
		convformula = function(value) return value / 47.45 end,
	},
	["plate"] = {
		idx = 3,
		name = "#tool.gruletool.unit.plate",
		sname = "#tool.gruletool.unit.splate",
		lname = "#tool.gruletool.unit.lplate",
		noscale = true,
		convformula = function(value) return value / 3 end,
	},
	["inch"] = {
		idx = 4,
		name = "#tool.gruletool.unit.inch",
		sname = "#tool.gruletool.unit.sinch",
		lname = "#tool.gruletool.unit.linch",
		convformula = function(value) return value end,
	},
	["yard"] = {
		idx = 5,
		name = "#tool.gruletool.unit.yard",
		sname = "#tool.gruletool.unit.syard",
		lname = "#tool.gruletool.unit.lyard",
		convformula = function(value) return value / 36 end,
	},
	["feet"] = {
		idx = 6,
		name = "#tool.gruletool.unit.feet",
		sname = "#tool.gruletool.unit.sfeet",
		lname = "#tool.gruletool.unit.lfeet",
		convformula = function(value) return value / 12 end,
	},
	["millimeter"] = {
		idx = 7,
		name = "#tool.gruletool.unit.millimeter",
		sname = "#tool.gruletool.unit.smillimeter",
		lname = "#tool.gruletool.unit.lmillimeter",
		convformula = function(value) return value * 25.4 end,
	},
	["centimeter"] = {
		idx = 8,
		name = "#tool.gruletool.unit.centimeter",
		sname = "#tool.gruletool.unit.scentimeter",
		lname = "#tool.gruletool.unit.lcentimeter",
		convformula = function(value) return value * 2.54 end,
	},
	["decimeter"] = {
		idx = 9,
		name = "#tool.gruletool.unit.decimeter",
		sname = "#tool.gruletool.unit.sdecimeter",
		lname = "#tool.gruletool.unit.ldecimeter",
		convformula = function(value) return value * 0.254 end,
	},
	["meter"] = {
		idx = 10,
		name = "#tool.gruletool.unit.meter",
		sname = "#tool.gruletool.unit.smeter",
		lname = "#tool.gruletool.unit.lmeter",
		convformula = function(value) return value * 0.0254 end,
	},
	["kilometer"] = {
		idx = 11,
		name = "#tool.gruletool.unit.kilometer",
		sname = "#tool.gruletool.unit.skilometer",
		lname = "#tool.gruletool.unit.lkilometer",
		convformula = function(value) return value * 0.0000254 end,
	},
	["megameter"] = {
		idx = 12,
		name = "#tool.gruletool.unit.megameter",
		sname = "#tool.gruletool.unit.smegameter",
		lname = "#tool.gruletool.unit.lmegameter",
		convformula = function(value) return value * 2.54e-8 end,
	},
	["gigameter"] = {
		idx = 13,
		name = "#tool.gruletool.unit.gigameter",
		sname = "#tool.gruletool.unit.sgigameter",
		lname = "#tool.gruletool.unit.lgigameter",
		convformula = function(value) return value * 2.54e-11 end,
	},
	["terameter"] = {
		idx = 14,
		name = "#tool.gruletool.unit.terameter",
		sname = "#tool.gruletool.unit.sterameter",
		lname = "#tool.gruletool.unit.lterameter",
		convformula = function(value) return value * 2.54e-14 end,
	},
	["astrounit"] = {
		idx = 15,
		name = "#tool.gruletool.unit.astrounit",
		sname = "#tool.gruletool.unit.sastrounit",
		lname = "#tool.gruletool.unit.lastrounit",
		convformula = function(value) return value / 5889679948818.9 end,
	},
	["lightyear"] = {
		idx = 16,
		name = "#tool.gruletool.unit.lightyear",
		sname = "#tool.gruletool.unit.slightyear",
		lname = "#tool.gruletool.unit.llightyear",
		convformula = function(value) return value / 3.724697e17 end,
	},
	["parsec"] = {
		idx = 17,
		name = "#tool.gruletool.unit.parsec",
		sname = "#tool.gruletool.unit.sparsec",
		lname = "#tool.gruletool.unit.lparsec",
		convformula = function(value) return value / 1.21483369e18 end,
	},
	["kiloparsec"] = {
		idx = 18,
		name = "#tool.gruletool.unit.kiloparsec",
		sname = "#tool.gruletool.unit.skiloparsec",
		lname = "#tool.gruletool.unit.lkiloparsec",
		convformula = function(value) return value / 1.21483369e21 end,
	},
	["megaparsec"] = {
		idx = 19,
		name = "#tool.gruletool.unit.megaparsec",
		sname = "#tool.gruletool.unit.smegaparsec",
		lname = "#tool.gruletool.unit.lmegaparsec",
		convformula = function(value) return value / 1.21483369e24 end,
	},
	["gigaparsec"] = {
		idx = 20,
		name = "#tool.gruletool.unit.gigaparsec",
		sname = "#tool.gruletool.unit.sgigaparsec",
		lname = "#tool.gruletool.unit.lgigaparsec",
		convformula = function(value) return value / 1.21483369e27 end,
	},
	["teraparsec"] = {
		idx = 21,
		name = "#tool.gruletool.unit.teraparsec",
		sname = "#tool.gruletool.unit.steraparsec",
		lname = "#tool.gruletool.unit.lteraparsec",
		convformula = function(value) return value / 1.21483369e30 end,
	},
	["mile"] = {
		idx = 22,
		name = "#tool.gruletool.unit.mile",
		sname = "#tool.gruletool.unit.smile",
		lname = "#tool.gruletool.unit.lmile",
		convformula = function(value) return value / 63360 end,
	},
	["naumile"] = {
		idx = 23,
		name = "#tool.gruletool.unit.naumile",
		sname = "#tool.gruletool.unit.snaumile",
		lname = "#tool.gruletool.unit.lnaumile",
		-- 1 Milla Náutica = exactamente 1852 metros. Convertimos pulgadas a metros y dividimos.
		convformula = function(value) return (value * 0.0254) / 1852 end,
	},
}